### Pandas-DataFrame and Series

#### Pandas is a powerful data manipulation library in Python , widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a dataframe is a two-dimensional, size-mutable, and potentially hererogeneous tabular data structure with labeled axes (rows and columns)

In [1]:
import pandas as pd

In [2]:
##Series

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
## Creating a series from a dictionary

data={'a':1,'b':2,'c':3}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30,40,50]

index=['a','b','c','d','e']
pd.Series(data,index=index)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
##DataFrame
## Creating a DataFrame from a dictionary

data={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['New York','Los Angeles','Chicago']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
<class 'pandas.DataFrame'>

In [6]:
## Create a dataframe from a list of dictionaries

data=[
    {'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'Los Angeles'},
    {'Name':'Charlie','Age':35,'City':'Chicago'}
]

df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [11]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [12]:
df.tail(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
51285,CA-2014-115427,31/12/2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31/12/2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31/12/2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31/12/2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31/12/2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [17]:
##Accessing Data from dataframe

data

[{'Name': 'Alice', 'Age': 25, 'City': 'New York'},
 {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
 {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}]

In [7]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [8]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [9]:
type(df['Name'])

pandas.Series

In [10]:
df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [11]:
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [12]:
##Accessing a specific element

df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [13]:
df.at[0,'Name']

'Alice'

In [14]:
df.iat[2,2]

'Chicago'

In [ ]:
##Data Manipulation with dataframe

##Adding a column
df['Salary']=[50000,70000,40000]
df

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   70000
2  Charlie   35      Chicago   40000

In [ ]:
##Remove a column
df.drop('Salary',axis=1,inplace=True) #axis=1 is used to confirm that you want to remove a column while inplace is used to make the change permanent

In [19]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [20]:
##Adding age to the column
df['Age']=df['Age']+1

In [21]:
df

      Name  Age         City
0    Alice   26     New York
1      Bob   31  Los Angeles
2  Charlie   36      Chicago

In [22]:
df.drop(1,inplace=True)

In [23]:
df

      Name  Age      City
0    Alice   26  New York
2  Charlie   36   Chicago

In [24]:
# Display the data types of each column
print('Data types:\n', df.dtypes)

# Describe the dataframe
print('statistical summary:\n', df.describe())

Data types:
 Name      str
Age     int64
City      str
dtype: object
statistical summary:
              Age
count   2.000000
mean   31.000000
std     7.071068
min    26.000000
25%    28.500000
50%    31.000000
75%    33.500000
max    36.000000