In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


#loading data
dataset= load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()


#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\hp\Desktop\programming\Pythonsection\LearningMachines\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df.sample(4)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
651271,Senior Data Analyst,Risk Data Analyst Senior,Spain,via BeBee,Full-time,False,Spain,2023-07-20 10:51:05,False,False,Spain,NaN,NaN,NaN,BANCO SANTANDER S.A.,['excel'],{'analyst_tools': ['excel']}
284091,Business Analyst,Rust Engineer,"Madrid, Spain",via BeBee,Full-time,False,Spain,2023-07-01 07:19:45,True,False,Spain,NaN,NaN,NaN,Q-Tech,"['rust', 'sql', 'mysql', 'aws', 'graphql', 'li...","{'cloud': ['aws'], 'databases': ['mysql'], 'li..."
64223,Data Engineer,Confirmed Data Engineer,France,via BeBee,Full-time,False,France,2023-09-09 06:22:13,True,False,France,NaN,NaN,NaN,Starther,NaN,NaN
302329,Data Scientist,SAS Data Scientist/Modeler engineer,"Chennai, Tamil Nadu, India",via Trabajo.org,Full-time,False,India,2023-08-01 17:19:54,False,False,India,NaN,NaN,NaN,Anicalls (Pty) Ltd,NaN,NaN

In [3]:
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')
df.sample(4)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
81581,Data Scientist,Junior Data Scientist (M/F),"Porto, Portugal",via Sercanto,Full-time,False,Portugal,2023-05-30 00:27:04,False,False,Portugal,NaN,NaN,NaN,Akapeople,"['python', 'r', 'sql', 'keras', 'spark', 'powe...","{'analyst_tools': ['power bi'], 'libraries': [...",May
519381,Data Analyst,Data Analyst,"Bologna, Metropolitan City of Bologna, Italy",via BeBee,Full-time,False,Italy,2023-03-11 11:23:07,False,False,Italy,NaN,NaN,NaN,Business Integration Partners S.p.A.,"['scala', 'sql', 'sas', 'sas', 'python', 'vba'...","{'analyst_tools': ['sas', 'excel', 'ms access'...",Mar
79973,Data Scientist,Data science internship,"San Francisco, CA",via Talent.com,Full-time,False,"California, United States",2023-09-01 00:05:52,False,False,United States,NaN,NaN,NaN,Reesby IT,"['r', 'sql', 'python', 'scala', 'java', 'c++',...","{'analyst_tools': ['tableau'], 'libraries': ['...",Sep
395070,Data Engineer,"Data Engineer II, Prime Video's Content Data P...",Australia,via Trabajo.org,Full-time,False,Australia,2023-07-16 18:17:05,True,False,Australia,NaN,NaN,NaN,Amazon Services Inc.,"['sql', 'c++', 'c#', 'java', 'python', 'golang...","{'cloud': ['aws', 'redshift', 'oracle'], 'libr...",Jul

In [10]:

"""dict_months={
         'Jan':df_jan,
         'Feb':df_feb,
         'Mar':df_mar,
         'Apr':df_apr,
         'May':df_may,
         'Jun':df_jun,
         'Jul':df_jul,
         'Aug':df_aug,
         'Sep':df_sep,
         'Oct':df_oct,
         'Nov':df_nov,
         'Dec':df_dec
      }"""



months =df['job_posted_month'].unique()

dict_months={month:df[df['job_posted_month'] == month] for month in months}

dict_months['Dec']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,NaN,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ...",Dec
12,Data Analyst,Stagiaire Data Analyst (H/F) - Lyon (69006),"Lyon, France",via Jobijoba,Full-time and Internship,False,France,2023-12-22 13:24:41,False,False,France,NaN,NaN,NaN,Engie,"['sql', 'php', 'excel', 'power bi', 'sap', 'ji...","{'analyst_tools': ['excel', 'power bi', 'sap']...",Dec
82,Data Engineer,Cbi Application Data Design Engineer,Singapore,via BeBee Singapore,Full-time,False,Singapore,2023-12-24 13:17:39,False,False,Singapore,NaN,NaN,NaN,Siemens,NaN,NaN,Dec
86,Data Engineer,Data Engineer,"Ridgefield Park, NJ",via SimplyHired,Full-time and Temp work,False,Sudan,2023-12-22 13:58:46,False,False,Sudan,NaN,NaN,NaN,Smartfox LLC,"['java', 'python', 'php', 'sql', 'shell', 'gcp...","{'cloud': ['gcp', 'aws'], 'libraries': ['spark...",Dec
89,Senior Data Engineer,Senior/Lead Data Engineer,"Dover, DE",via SaluteMyJob,Full-time and Part-time,False,"Illinois, United States",2023-12-04 13:08:34,False,True,United States,NaN,NaN,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az...",Dec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785609,Data Engineer,Data Engineer,"Ho Chi Minh City, Vietnam",via Trabajo.org,Full-time,False,Vietnam,2023-12-17 06:23:18,False,False,Vietnam,NaN,NaN,NaN,Fram^,"['sql', 'nosql', 'postgresql', 'mysql', 'spark...","{'databases': ['postgresql', 'mysql'], 'librar...",Dec
785623,Data Engineer,Data Engineer,"Gothenburg, Sweden",via Trabajo.org,Full-time,False,Sweden,2023-12-13 06:49:09,False,False,Sweden,NaN,NaN,NaN,Avigna AB,NaN,NaN,Dec
785640,Data Analyst,Data Analyst Lead,Thailand,via Trabajo.org,Full-time,False,Thailand,2023-12-17 06:16:04,False,False,Thailand,NaN,NaN,NaN,"Siam Piwat Co., Ltd.","['sql', 'python', 'pyspark', 'excel', 'spreads...","{'analyst_tools': ['excel', 'spreadsheet'], 'l...",Dec
785662,Business Analyst,Business Analysis and Intelligence Manager,"Kuala Lumpur, Federal Territory of Kuala Lumpu...",via Trabajo.org,Full-time,False,Malaysia,2023-12-05 06:22:35,False,False,Malaysia,NaN,NaN,NaN,Denave (M) Sdn Bhd,"['sql', 'sql server', 'excel', 'word', 'power ...","{'analyst_tools': ['excel', 'word', 'power bi'...",Dec
785677,Cloud Engineer,"Engineer 3, Facilities","Penang, Malaysia",via Smart Recruiters Jobs,Full-time,False,Malaysia,2023-12-21 06:12:22,False,False,Malaysia,NaN,NaN,NaN,Western Digital,NaN,NaN,Dec

In [11]:
pd.concat([dict_months['Jan'], dict_months['Feb'], dict_months['Mar'], dict_months['Apr']], ignore_index=True)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
0,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",Jan
1,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,NaN,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear...",Jan
2,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,NaN,NaN,NaN,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",Jan
3,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,NaN,NaN,NaN,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws']...",Jan
4,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,NaN,NaN,NaN,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python',...",Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283398,Software Engineer,Software Engineering Student,"Tel Aviv-Yafo, Israel",via Trabajo.org,Full-time,False,Israel,2023-04-11 06:52:21,False,False,Israel,NaN,NaN,NaN,VAST Data,['linux'],{'os': ['linux']},Apr
283399,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':...",Apr
283400,Software Engineer,Integration Analyst,"Łódź, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,NaN,NaN,NaN,Team Quest,"['sql', 'oracle', 'aws', 'sap', 'atlassian']","{'analyst_tools': ['sap'], 'cloud': ['oracle',...",Apr
283401,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}",Apr
283402,Business Analyst,Aeronautical Analyst,"Gdańsk, Poland",via Praca Trabajo.org,Full-time,False,Poland,2023-04-26 06:24:52,False,False,Poland,NaN,NaN,NaN,NAVBLUE,NaN,NaN,Apr