In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


#loading data
dataset= load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()


#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\hp\Desktop\programming\Pythonsection\LearningMachines\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.sample(4)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
15908,Machine Learning Engineer,Machine Learning Engineer,"Copenhagen, Denmark",via BeBee Danmark,Full-time,False,Denmark,2023-06-14 13:25:38,False,False,Denmark,NaN,NaN,NaN,"Workday, Inc.","['python', 'aws', 'numpy', 'pandas', 'tensorfl...","{'cloud': ['aws'], 'libraries': ['numpy', 'pan..."
300968,Data Engineer,Data Engineer (m/f/d) - Network Planning,"Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-05-17 17:40:33,True,False,Germany,NaN,NaN,NaN,Flix,"['python', 'r', 'sql', 'postgresql', 'snowflak...","{'cloud': ['snowflake', 'aws'], 'databases': [..."
252066,Data Analyst,Data Analyst/ETL Tester - Now Hiring,"Washington, DC",via Snagajob,Full-time,False,"New York, United States",2023-02-04 07:00:22,False,False,United States,NaN,NaN,NaN,Pyramid Systems,"['sql', 'oracle', 'excel', 'git']","{'analyst_tools': ['excel'], 'cloud': ['oracle..."
115508,Data Engineer,"Staff Data Engineer (Spark, Python, Hadoop)","Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 08:30:52,False,False,India,year,147500.0,NaN,Visa,"['java', 'nosql', 'sas', 'sas', 'db2', 'mysql'...","{'analyst_tools': ['sas'], 'databases': ['db2'..."

In [5]:
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')
df.sample(4)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
198251,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Spain,2023-03-09 15:22:38,True,False,Spain,NaN,NaN,NaN,Akuaro,"['sql', 'python', 'java', 'dynamodb', 'azure',...","{'cloud': ['azure', 'aws', 'redshift'], 'datab...",Mar
322253,Data Analyst,Material Data Analyst,Anywhere,via Indeed,Full-time,True,"Florida, United States",2023-03-15 17:02:32,False,True,United States,NaN,NaN,NaN,Material Bank,['excel'],{'analyst_tools': ['excel']},Mar
96787,Data Analyst,Data Analyst,Singapore,via Jobrapido.com,Full-time,False,Singapore,2023-11-21 00:26:34,False,False,Singapore,NaN,NaN,NaN,Jobline Resources Pte Ltd,"['sql', 'python', 'aws', 'excel', 'tableau', '...","{'analyst_tools': ['excel', 'tableau', 'power ...",Nov
515731,Data Engineer,Data Engineer (Spark Developer),Dubai - United Arab Emirates,via Indeed,Full-time,False,United Arab Emirates,2023-05-02 11:27:09,False,False,United Arab Emirates,NaN,NaN,NaN,Experts Plus Recruitment Services,"['sql', 'scala', 'java', 'python', 'nosql', 'o...","{'cloud': ['oracle'], 'libraries': ['spark', '...",May

In [ ]:
7:30:15